from .save_webp_sequence import (
    NODE_CLASS_MAPPINGS as SAVE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SAVE_NAMES,
)
from .load_image_sequence import (
    NODE_CLASS_MAPPINGS as SEQ_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SEQ_NAMES,
)
from .load_image_list import (
    NODE_CLASS_MAPPINGS as LIST_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LIST_NAMES,
)
from .list_video_files import (
    NODE_CLASS_MAPPINGS as VIDEO_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_NAMES,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(SAVE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SEQ_MAPPINGS)
NODE_CLASS_MAPPINGS.update(LIST_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VIDEO_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(SAVE_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(SEQ_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(LIST_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_NAMES)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
